### ISSUE TITLE
Getting into shell

### ISSUE THREAD

**Issue by TheeMadWhiteHatter** [ciena/ciena.saos10#4]
How do I get into diag shell host mode from ansible? When running the following
command:
- diag shell host

I just get a timeout and it never enters shell mode

**Comment by jgroom33** [comment]
thanks @ogowen45 
The prompt match didn't account for that.  I just updated it to add support.
#5 
reinstall the collection and it should work.

**Comment by TheeMadWhiteHatter** [comment]
Thank you, works great. Much appreciated.
