### ISSUE TITLE
Classifier import module error

### ISSUE THREAD

**Issue by lucasw-eng** [ciena/ciena.saos10#6]
When attempting to use the following module I get the error below:

ciena.saos10.saos10_classifiers

```
fatal: [<hostname>]: FAILED! => {
    "msg": "Could not find imported module support code for ansible_collections.ciena.saos10.plugins.modules.saos10_classifiers.  Looked for (['ansible_collections.ciena.saos10.plugins.module_utils.network.saos10.config.classifiers.classifiers.Classifiers', 'ansible_collections.ciena.saos10.plugins.module_utils.network.saos10.config.classifiers.classifiers'])"
}
```

It seems to be trying to import a class method/module that does not exist. I am using Ansible version 2.12.1.

**Comment by jgroom33** [comment]
Thanks @braincan .  The file is there: https://github.com/ciena/ciena.saos10/blob/master/plugins/modules/saos10_classifiers.py
do other modules work?

**Comment by lucasw-eng** [comment]
Hi @jgroom33, if I'm reading the above error wrong it's not looking for the class nested under the 'modules' directory, but the one under the module_utils/network/saos10/config/classifiers.py which I don't see in the repo or in the install I performed. 

As far as the other modules yes the other three work as documented.

**Comment by lucasw-eng** [comment]
So, using the ciena/resource_module_builder I generated the necessary configuration files (it seems the ansible-galaxy install didn't include them). With those generated files I can now get facts on classifiers, but when trying to modify the configuration using either merged/overridden state's I get the following error: 

`fatal: [<REMOVED>]: FAILED! => {"changed": false, "module_stderr": "/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible_collections/ciena/saos10/plugins/module_utils/network/saos10/facts/classifiers/classifiers.py:78: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.\nTraceback (most recent call last):\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible/module_utils/connection.py\", line 147, in _exec_jsonrpc\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py\", line 234, in dumps\n    return cls(\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py\", line 199, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible/module_utils/common/json.py\", line 82, in iterencode\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py\", line 257, in iterencode\n    return _iterencode(o, 0)\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible/module_utils/common/json.py\", line 71, in default\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py\", line 179, in default\n    **raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type _Element is not JSON serializable\n\nDuring handling of the above exception**, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/lucasw/.ansible/tmp/ansible-local-43619nh16ja40/ansible-tmp-1643821640.551735-43623-244629485057088/AnsiballZ_saos10_classifiers.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/lucasw/.ansible/tmp/ansible-local-43619nh16ja40/ansible-tmp-1643821640.551735-43623-244629485057088/AnsiballZ_saos10_classifiers.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/lucasw/.ansible/tmp/ansible-local-43619nh16ja40/ansible-tmp-1643821640.551735-43623-244629485057088/AnsiballZ_saos10_classifiers.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ciena.saos10.plugins.modules.saos10_classifiers', init_globals=dict(_module_fqn='ansible_collections.ciena.saos10.plugins.modules.saos10_classifiers', _modlib_path=modlib_path),\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible_collections/ciena/saos10/plugins/modules/saos10_classifiers.py\", line 212, in <module>\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible_collections/ciena/saos10/plugins/modules/saos10_classifiers.py\", line 207, in main\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible_collections/ciena/saos10/plugins/module_utils/network/saos10/config/classifiers/classifiers.py\", line 66, in execute_module\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible_collections/ciena/saos10/plugins/module_utils/network/saos10/config/classifiers/classifiers.py\", line 103, in set_config\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible_collections/ciena/saos10/plugins/module_utils/network/saos10/config/classifiers/classifiers.py\", line 129, in set_state\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py\", line 77, in __rpc__\n  File \"/var/folders/64/l36sk2sj0hd7rv0fbm768xw00000gn/T/ansible_ciena.saos10.saos10_classifiers_payload_0h5aj3_d/ansible_ciena.saos10.saos10_classifiers_payload.zip/ansible/module_utils/connection.py\", line 149, in _exec_jsonrpc\nansible.module_utils.connection.ConnectionError: Failed to encode some variables as JSON for communication with ansible-connection. The original exception was: Object of type _Element is not JSON serializable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}` - I bolded what I think is the true error.

**Comment by jgroom33** [comment]
Thanks @braincan 
We're actively developing the resource module builder to generate accurate modules. I'll get something that works out shortly.
